# Generated by Django 4.1.7 on 2023-03-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(choices=[('apple', 'apple'), ('samsung', 'samsung'), ('oneplus', 'oneplus'), ('redmi', 'redmi'), ('realme', 'realme'), ('oppo', 'oppo')], max_length=100)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
